### PR TITLE
I have started section 2 please tell me if I can add anything or make it better in anyway

### PR DESCRIPTION
**Pull request by bkkcreative19**

### CODE REVIEW

**Comment by briancodex** [comment]
check the new repo. Looks like your section overlaps the hero section. I'm not sure if that's because of the hero section css or your section css

**Comment by bkkcreative19** [comment]
What do you mean because on my view it is not overlapping.

**Comment by briancodex** [comment]
Screen Shot 2020-12-20 at 5 53 48 PM

Screen Shot 2020-12-20 at 5 54 13 PM

One image is from a larger desktop screen and the other is on a smaller laptop screen

**Comment by briancodex** [comment]
I'll create a new issue and see if anyone wants to fix it

**Pull request merged**
